### ISSUE TITLE
Logged Out > Black Screen > Crashed

### ISSUE THREAD

**Issue by Beherrit** [goatcorp/FFXIVQuickLauncher#879]
System.InvalidOperationException: Process was not started by this object, so requested information cannot be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 602

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: E:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by Delta87** [comment]
Maybe an you should update your XiV-Launcher. Your version is 6.2.28.0, but the current ist 6.2.29.0

**Comment by lmcintyre** [comment]
Should be fixed now, please restart XIVLauncher and update.

**Comment by Beherrit** [comment]
Appears to be working now.  Appreciate the work there Imcintyre. Delta... that crash regardless of version is still not expected behaviour, at least I wouldnt think it is expected.
